---
version: 2

updates:
  - package-ecosystem: "devcontainers"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: ":dependabot: devcontainers"
      include: "scope"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: ":dependabot: github-actions"
      include: "scope"
  - package-ecosystem: "uv"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: ":dependabot: uv"
      include: "scope"
