[project]
name = "good-repo-poc"
version = "0.0.1"
description = "Proof of Concept of a good repository"
readme = "README.md"
requires-python = ">=3.12"
dependencies = []

[dependency-groups]
dev = [
    "pre-commit==4.2.0",
]
