---
name: 🧪 Test

on:
  pull_request:
    branches:
      - main

permissions: {}

jobs:
  container-structure-test:
    name: Container Structure Test
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Monitor GitHub Actions Permissions
        id: monitor_permissions
        uses: GitHubSecurityLab/actions-permissions/monitor@31cf7361439cbdffbc73a3bb138b7e1662d46c9b # v1.0.2-beta6

      - name: Harden Runner
        id: harden_runner
        uses: step-security/harden-runner@6c439dc8bdf85cadbbce9ed30d1c7b959517bc49 # v2.12.2
        with:
          egress-policy: audit

      - name: Checkout
        id: checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false

      - name: Set Up Container Structure Test
        id: setup_container_structure_test
        uses: ministryofjustice/analytical-platform-github-actions/setup-container-structure-test@e0b96059804cbe750acb4a495ec6106617972f0b # v4.1.0

      - name: Build
        id: build
        uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 # v6.18.0
        with:
          file: Dockerfile
          context: .
          push: false
          tags: ${{ github.sha }}

      - name: Container Structure Test
        id: container_structure_test
        shell: bash
        run: |
          container-structure-test test --platform linux/amd64 --config test/container-structure-test.yml --image ${{ github.sha }}
